### ISSUE TITLE
Move Kibana dashboard to PROD

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#111]
To move
1. EMFOS SCHEDULES
2. EMFOS OPDE MODELS
3. EMFOS TASKS

**Comment by Haigutus** [comment]
Also implement tag "draft" to unfinished dashboards

**Comment by mr0321** [comment]
Kibana dashboards were exported by script and imported to prod Kibana manually. Import consisted of 3 dashboards: EMFOS OPDE SCHEDULE, EMFOS OPDE MODELS and EMFOS TASKS along with the dependencies
