### ISSUE TITLE
MODEL RETRIEVER - StreamLostError

### ISSUE THREAD

**Issue by MK1295** [Baltic-RCC/EMF#113]
Task working for 3-9minutes, gives out an error: StreamLostError
![image](https://github.com/Baltic-RCC/EMF/assets/136691671/d86863af-5b79-477d-9fd8-b24e84b12d30)

**Comment by Haigutus** [comment]
Please include the original error, currently log is incomplete

**Comment by MK1295** [comment]
Log provided in teams chat.  file:model_retriever_prod
