### ISSUE TITLE
Task Scheduler empty inclusion properties takes no models

### ISSUE THREAD

**Issue by VeikoAunapuu** [Baltic-RCC/EMF#119]
Also * setting takes no models. 
![image](https://github.com/Baltic-RCC/EMF/assets/23611937/f7cafbf9-8465-458f-8737-c02ac5b7cede)

Update so that * includes all and empty includes none.

**Comment by Haigutus** [comment]
Fix in dev branch, now with both list empty, all available models should be used.
@VeikoAunapuu please test

**Comment by Haigutus** [comment]
Solved
