### ISSUE TITLE
Testing psybl 1.7.0

### ISSUE THREAD

**Issue by VeikoAunapuu** [Baltic-RCC/EMF#160]

**Comment by mr0321** [comment]
Regarding to the failing buses last release of open-loadflow is from July (https://github.com/powsybl/powsybl-open-loadflow/releases), fix was merged in August, https://github.com/Baltic-RCC/EMF/tree/mr-revert-failed-buses-back still has main solution

**Comment by VeikoAunapuu** [comment]
No large benefits to update at this point.
