### ISSUE TITLE
Replacement logic for week ahead and month ahead merges

### ISSUE THREAD

**Issue by VeikoAunapuu** [Baltic-RCC/EMF#176]
For week ahead and month ahead merge to use logic to look for same timetamp or for year ahead look for closest year ahead model. 

Plan would be to add to replacement_config:
 "timeHorizon": { "Request_list": ["ID", "1D", "2D", "WK", "M-1", "Y-1"]

Ex. If week ahead model is not available it would look for M-1 model, if that is not available for the excpected time it will search the closest Y-1 model available based on scenario_time. 

Ex2. If month ahead model is not available it will look for the closest year ahead model.

**Comment by MK1295** [comment]
20250115T0930Z - from 1st January 2025 to 28th February 2025.[WINTER 1]
20250416T0830Z - from 1st March 2025 to 31st May 2025.[SPRING]
20250716T0830Z -from 1st June 2025 to 31st August 2025[SUMMER]
20251015T0830Z - from 1st September 2025 to 30th November 2025[AUTUMN]
20251217T0930Z - from 1st December 2025 to 31st December 2025[WINTER 2]

**Comment by VeikoAunapuu** [comment]
Propsal to use: "timeHorizon": { "Request_list": ["ID", "1D", "2D", "WK", "M-1", "1D", "Y-1"]

**Comment by MK1295** [comment]
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>



  | Run   day/time | Target   day/time | Reference   day/ | D   ISO/
-- | -- | -- | -- | --
D-1 | Wednesday   1900 | Thursday | Thursday | P1D
D-2 | Wednesday   1900 | Friday | Friday | P2D
D-3 | Wednesday   1900 | Saturday(19.10) | Saturday(12.10) | P7D
D-4 | Wednesday   1900 | Sunday | Sunday | P7D
D-5 | Wednesday   1900 | Monday | Wednesday(last available market data) | P5D
D-6 | Wednesday   1900 | Tuesday(22.10) | Wednesday(16.10) | P6D
D-7 | Wednesday   1900 | Wednesday | Wednesday | P7D
D-8 | Wednesday   1900 | Thursday | Wednesday | P8D
D-9 | Wednesday   1900 | Friday | Wednesday | P9D




</body>

</html>

**Comment by VeikoAunapuu** [comment]
for year ahead we use 
month (1)
 {1}
 {2]
