### ISSUE TITLE
Optimization tests

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#194]
Test if merge worker and model retriever continue to work and what is the memory and processing time impact

1. Set store CGMES extention to false iidm.import.cgmes.store-cgmes-model-as-network-extension
2. Try triplets 0.0.8 with pandas.read_RDF([path], data_type='string[pyarrow]', max_workers=4)
3. Try triplets 0.0.8 with pandas.read_RDF([path], max_workers=<4 for IGM><X for CGM)
4. Try triplets 0.0.8 with export_to_cimxml(max_workers=None

**Comment by mr0321** [comment]
Merge worker BA 14.11.2024 23.30Z 1D. Initial state:
![image](https://github.com/user-attachments/assets/ac3f7d2f-f3da-41ad-931c-a91445c949cc)

1. Set store CGMES extention to false iidm.import.cgmes.store-cgmes-model-as-network-extension
![image](https://github.com/user-attachments/assets/e0ef5231-ca55-48d3-98fa-c43637cd36ec)

**Comment by mr0321** [comment]
Model Retriever 14.11.2024 23.30Z 1D. Initial state: lacking models from OPDM (DATA: None)

**Comment by Haigutus** [comment]
TODO: Try with larger set of models

**Comment by mr0321** [comment]
Merge worker EU 18.11.2024 07.30Z 1D. Based on the merge_from_local  branch. Initial state (CPU >100% means 1+ core): 22 TSOs
![image](https://github.com/user-attachments/assets/c1c84719-9588-497e-8ba7-cf485bd93754)
_1. Set store CGMES extention to false iidm.import.cgmes.store-cgmes-model-as-network-extension_
![image](https://github.com/user-attachments/assets/8c9b3fc2-3d56-43d3-9890-62dbf9c1b428)
_2. Try triplets 0.0.8 with pandas.read_RDF([path], data_type='string[pyarrow]', max_workers=4)_
![image](https://github.com/user-attachments/assets/4365bf96-bde8-4b2c-a2e1-effb7bd6f2e4)
_3. Try triplets 0.0.8 with pandas.read_RDF([path], max_workers=<4 for IGM><X for CGM):_ X = 4
![image](https://github.com/user-attachments/assets/330979a9-d718-4664-aa16-b67528680f87)
_4.Try triplets 0.0.8 with export_to_cimxml(max_workers=None max_workers=None_ is set as default:
![image](https://github.com/user-attachments/assets/21095b2b-5f71-4f3e-a527-4f673b2e6a19)
