### ISSUE TITLE
Query operation with specific metadata is always sent on the model before executing the GetContent

### ISSUE THREAD

**Issue by VeikoAunapuu** [Baltic-RCC/EMF#196]

**Comment by Haigutus** [comment]
Does not seem to be the case

Worker gets the context from subscribed metadata object, no additional query is made -> https://github.com/Baltic-RCC/EMF/blob/634c30ada38ae866bbce8205775814838c96eabf/emf/model_retriever/model_retriever.py#L36

There is an implementation in OPDM integrations, that first makes metadata query, but this is not used currenlty (maybe used in future, to cold start the application, if no matadata is available) ->
https://github.com/Baltic-RCC/EMF/blob/634c30ada38ae866bbce8205775814838c96eabf/emf/common/integrations/opdm.py#L109
