### ISSUE TITLE
QAS Reports

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#21]
- [x] Find pure python XSLT engine/library
- [ ] Refactor  internal EMF code and port it over

**Comment by VeikoAunapuu** [comment]
[qar_xlst_example.zip](https://github.com/Baltic-RCC/EMF/files/14915131/qar_xlst_example.zip)

STEP1: IGM validation added into validation handler
STEP2: CGM validation added to merge handler

**Comment by VeikoAunapuu** [comment]
Qintautas made a internal format that sends to rabbit the information,. Close this and continue under #64 and #65
