### ISSUE TITLE
Task Scheduler Finalization

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#27]
- [x] Create integration to publish tasks to Rabbit MQ
- [x] Configure to run on Jenkins (every minute for next minute)
- [x] #86
- [x] #97
- [x] #98
- [ ] #88

Current Code: https://github.com/Baltic-RCC/EMF/blob/main/emf/task_generator/task_generator.py

**Comment by VeikoAunapuu** [comment]
#60  merge request
