### ISSUE TITLE
Containerisaton

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#3]
Add to wiki main principles how we package the code as small docker based services

Base service image build
- base image
- package management
- artifactory
- security considerations

Deployment pipeline
- configuration management

**Comment by Haigutus** [comment]
Example how we have done it previously - https://github.com/Haigutus/rabbit_xml_gate/blob/master/Dockerfile

**Comment by The-Magicians-Code** [comment]
Can be assigned to me with requested features/notes

**Comment by Haigutus** [comment]
To be assigned to Tanel

**Comment by The-Magicians-Code** [comment]
Problem when building [Dockerfile](https://github.com/Baltic-RCC/EMF/blob/edecafb04a1ae23b5afc473f623355e745045ec0/Dockerfile), pypowsybl does not install, gives error:
<img width="999" alt="image" src="https://github.com/Baltic-RCC/EMF/assets/60236942/035aeb4a-aeba-44c3-9477-4e5b3925030d">
/bin/sh: 1: /bin/native-image: not found

Tried a solution which did not yield any positive results:
https://www.graalvm.org/latest/reference-manual/native-image/

**Comment by The-Magicians-Code** [comment]
Solution:
Image successfully built on x86 Linux, MacOS version has to be built and compiled by the user

**Comment by Haigutus** [comment]
First scope is Model Retriever
