### ISSUE TITLE
Schedules to ELK document id selection

### ISSUE THREAD

**Issue by m-karo** [Baltic-RCC/EMF#32]
Need to figure out how properly select document id in order to be able to overwrite document by each revision number.

Now id is generated from mRID, revisionNumber, TimeSeries.mRID and position. This is not good as revision number is included makes it different for each revision.

![image](https://github.com/Baltic-RCC/EMF/assets/61706345/23a7f5ec-0787-4c5f-8707-99d5ad3bab3a)

**Comment by Haigutus** [comment]
Options:

1. Keep all PEVF version (intraday is updated each hour) - add version in the _id string
2. Keep only latest version - remove version from _id string

In case 1, we can use document "created time" as filter to get latest version

Decision needed: To we keep all PEVF versions or not?

In option 1. we keep 2 versions of D-1 and 32 versions of ID
In option 2. we keep only one copy od D-1 and ID

**Comment by Haigutus** [comment]
2024-03-14 Decision: Keep only latest version for now, change if real need arises.

TODO: Remove "revisionNumber" from the _id

**Comment by Haigutus** [comment]
Options:

1. Keep all PEVF version (intraday is updated each hour) - add version in the _id string
2. Keep only latest version - remove version from _id string (keeps data per curve)
3. Keep data per MTU with unique ID

Options storage amount (per month):
1. 9-10gb of storage
2. 900MB 
3. 900MB

One file is estimated to take 10MB

We might need to separate indexes to weeks as we are storing too much data per one index


2024-03-25 Decision: Keep only latest version for now, change if real need arises. + Add to A03 parsing that for each MTU there would be a document.

**Comment by VeikoAunapuu** [comment]
IEC conversion to MTU implemented
