### ISSUE TITLE
Create Governance documentation

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#33]

**Comment by VeikoAunapuu** [comment]
initial version available here

**Comment by Haigutus** [comment]
Feedback from Anne
![image](https://github.com/Baltic-RCC/EMF/assets/11408965/f0092f3f-37ac-44aa-b147-d554b2a92e35)

**Comment by Haigutus** [comment]
@makkes please review

**Comment by VeikoAunapuu** [comment]
Integrated Anne remarks: https://github.com/Baltic-RCC/EMF/wiki/Governance
