### ISSUE TITLE
First version of Logging Module

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#4]

**Comment by Haigutus** [comment]
For logging following principle should be used:
- process_id:
	- persistent in time and fixed in settings
	- Definition: Process is the root structure and common denominator for configuration activity
	- Example: CGM Creation

- run_id:
	- persistent in time and fixed in settings
	- Example: D-1
	- Purpose: Aggregate all logs pertaining to a run within a process

- job_id:
	- generated on the go, UUID4.
	- Definition: Job is a concrete instance of a run.
	- Example: D-1 run for a given day is a job.
	- Purpose: Aggregate all logs pertaining to an instance of a run of a specific period

- task_id:
	- generated on the go, UUID4.
	- Example: All activity for a single Scenario Time within a given job is a task
	- Purpose: Get all logs for a specific task

**Comment by Haigutus** [comment]
All Logging related documentation can be added here: https://github.com/Baltic-RCC/EMF/wiki/Logging

**Comment by m-karo** [comment]
Initial version of ELK custom logger added.
