### ISSUE TITLE
Add example data to this repository

### ISSUE THREAD

**Issue by makkes** [Baltic-RCC/EMF#45]
As an engineer working with the code in this repository I want to run the EMF components locally using example data.

To be discussed:

- What kind of data do we need? Is it just different IGMs? @Haigutus, would you be able to answer this?

**Comment by Haigutus** [comment]
Use the ENTSO-E example models to generate dummy data or as Chavdar, if he has some models to share for this purpose

**Comment by mr0321** [comment]
Examples of using the ENTSOE zip (as is) are currently in [mr-validator_use_local_files](https://github.com/Baltic-RCC/EMF/tree/mr-validator_use_local_files)

**Comment by VeikoAunapuu** [comment]
Add relevant documentation on the solution

**Comment by VeikoAunapuu** [comment]
Documentation added, pullrequest #58
