### ISSUE TITLE
First version of Settings Module

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#5]

**Comment by m-karo** [comment]
Question what approach we are going to use for settings configuration. One centralized settings file which consists of parameters for all sub-modules of application or we are going to distrubute settings by each sub-module (lf engine, process scheduler and etc.)?

**Comment by Haigutus** [comment]
I would propose each module will have its own configuration/settings file. I have reflected in the Project Repository Structure - https://github.com/Baltic-RCC/EMF/wiki#project-folder-structure

**Comment by m-karo** [comment]
Initial version of application.properties parser added in source code.

**Comment by Haigutus** [comment]
@m-karo refactored the config parser.
