### ISSUE TITLE
Create Merge Worker

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#57]
- [x] Get Context from task message from RabbitMQ
- [x] Get Data from Object Storage
- [x] Publish data to Minio
- [ ] Publish Data to Object Storage
- [x] Publish Data to OPDM
- [ ] Get correct ID timeHorizon/process type

**Comment by mr0321** [comment]
![merger](https://github.com/Baltic-RCC/EMF/assets/145195994/a7b53031-c64c-4d89-a4b2-ac7b6683b6a8)

Current implementation (work in progress)
