### ISSUE TITLE
RMM process Implementation

### ISSUE THREAD

**Issue by VeikoAunapuu** [Baltic-RCC/EMF#66]
- [x] Implement include and exclude configuration usage for model inclusion
- [x] Implement local file import from minio based on conf
- [x] #89
- [x] #87
- [x] #91
- [x] #90
- [x] #102
- [ ] #110

**Comment by mr0321** [comment]
![merger_rmm](https://github.com/Baltic-RCC/EMF/assets/145195994/b536f33f-12ce-49ef-9e74-e3a74685efcd)

**Comment by Haigutus** [comment]
Lets close this ticket, only final conf missing from RMM worker in PROD
