### ISSUE TITLE
Seperate handler for Validation report sending and conversion 

### ISSUE THREAD

**Issue by VeikoAunapuu** [Baltic-RCC/EMF#72]
1. Seperate handlers for conversion
2. @gpoderys  add content for XML conversion and sending to rabbit (XML and XSL)

**Comment by mr0321** [comment]
Merge handler calls either validate_models or send_cgm_qas_report in validator.py
![merger_rmm](https://github.com/Baltic-RCC/EMF/assets/145195994/23fb2a68-51f2-40cf-bd19-ad6cbba9feb7)

**Comment by mr0321** [comment]
![merger_rmm](https://github.com/Baltic-RCC/EMF/assets/145195994/e25f4fea-6382-47f4-9456-5501dd47368e)

Add option to export full model (CGM + IGM's + BOUNDARY) or CGM only

**Comment by mr0321** [comment]
Clean up (remove redundant functions for getting boundary data):
![merger_rmm](https://github.com/Baltic-RCC/EMF/assets/145195994/cb69a3bc-0c79-499f-81d1-46b4d6dfa2be)

**Comment by VeikoAunapuu** [comment]
Will be managed under ticket #21
