### ISSUE TITLE
EIC to mRID map for Scaling

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#76]
python```def get_EIC_to_mRID_map(data, type):
    name_map = {"ID": "mRID", "VALUE": "EIC"}
    return triplets.rdf_parser.filter_triplet_by_type(data, type).drop_duplicates().query("KEY == 'IdentifiedObject.energyIdentCodeEic'")[name_map.keys()].rename(columns=name_map)```

**Comment by mr0321** [comment]
Script for creating the maps is situated under designated project
