### ISSUE TITLE
Support for BytesIO for pypowsybl

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#9]
- [x] 1. Import of CIM data
- [x] 2. Export of CIM data
- [x] 3. Refactor CIM import in our codebase
- [x] 4, Refactor CIM export in our codebase

https://github.com/powsybl/pypowsybl/issues/401

**Comment by m-karo** [comment]
Support implemented in v0.24. Helper function ammended to refactor opdm objects to BytesIO
![image](https://github.com/Baltic-RCC/EMF/assets/61706345/5366e8ff-778b-4d29-9de4-43223dafd9c5)

**Comment by Haigutus** [comment]
Opening to track export implementation

**Comment by Haigutus** [comment]
Export implementation by pypowsybl is done, we need to refactor our code
