### ISSUE TITLE
Tasks Rabbit PROD CONF

### ISSUE THREAD

**Issue by Haigutus** [Baltic-RCC/EMF#91]
#87

**Comment by MK1295** [comment]
In prod configured exchanges: 
emf.tasks
emfos.xslt
emfos.xslt.test
dev.null

configured queues:
xslt-endpoint
xslt-service
emf-merge.tasks.cgm
emf-merge.tasks.rmm
dead.letter

**Comment by MK1295** [comment]
added exchange:
opde-from.edx 
opde-to.edx
pdn-from.edx
pdn-to.edx


queues:
object-storage.models.opdm-metadata
object-storage.models.synchro
object-storage.models
pdn-to.edx
opde-to.edx

**Comment by Haigutus** [comment]
deleted
emfos.xslt.test
xslt-endpoint

**Comment by Haigutus** [comment]
consider exporting broker definitions from test and importing to prod (remove shovels manually from definitions)

**Comment by Haigutus** [comment]
25.06 will be active session to finalize config

**Comment by Haigutus** [comment]
Finalized by @VeikoAunapuu
